<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'helper.checkeree' shared autowired service.

include_once $this->targetDirs[3].'/src/Helper/Checker.php';

return $this->services['helper.checkeree'] = new \App\Helper\Checker();
