<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOEFdwJ8\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOEFdwJ8/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerOEFdwJ8.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerOEFdwJ8\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerOEFdwJ8\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'OEFdwJ8',
    'container.build_id' => '6807a243',
    'container.build_time' => 1539085841,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerOEFdwJ8');
