<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEdhDFFt\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEdhDFFt/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerEdhDFFt.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerEdhDFFt\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerEdhDFFt\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'EdhDFFt',
    'container.build_id' => 'aec1dc03',
    'container.build_time' => 1539096166,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerEdhDFFt');
